services:
  cms:
    image: insurance-cms:latest
    container_name: insurance-cms
    environment:
      PORT: 3000
      NODE_ENV: production
      NEXT_TELEMETRY_DISABLED: 1
      CORE_API_URL: http://insurance-core-api:8080
    ports:
      - "3000:3000"
    restart: unless-stopped
