services:
  cms:
    image: insurance-cms:latest
    container_name: insurance-cms
    environment:
      PORT: 3000
      NODE_ENV: production
      NEXT_TELEMETRY_DISABLED: 1
      CORE_API_URL: http://172.17.0.1:8080
      MOCK_CORE_API: "false"
      USE_MOCK_DATA: "false"
    ports:
      - "3000:3000"
    restart: unless-stopped
