import {
  IDashboardRepository,
  DashboardData,
} from './dashboard.repository.interface';

export class DashboardMockRepository implements IDashboardRepository {
  private data: DashboardData = {
    kpis: {
      totalApplications: {
        title: 'Total Pengajuan Masuk',
        value: '1.284',
        trend: '+14.8%',
        trendDirection: 'up',
        subtitle: 'vs bulan lalu',
        note: '85% Target kuartal 3',
        icon: '📋',
        color: '#2563eb',
      },
      inReview: {
        title: 'Dalam Review Underwriting',
        value: '28',
        trend: '18.4 min',
        trendDirection: 'neutral',
        subtitle: 'Rata-rata SLA saat ini',
        note: '2 mendekati batas SLA',
        icon: '⏳',
        color: '#f59e0b',
      },
      approvalRate: {
        title: 'Approval Rate Otomatis',
        value: '94.2%',
        trend: 'SLA Compliant',
        trendDirection: 'up',
        subtitle: 'Standar OJK terpenuhi',
        note: 'Dukcapil OCR instant pass',
        icon: '⚡',
        color: '#10b981',
      },
      activePolicies: {
        title: 'Polis Aktif Diterbitkan',
        value: '1.142',
        trend: 'Rp 8.42 M',
        trendDirection: 'up',
        subtitle: 'Gross Written Premium',
        note: 'Portofolio sehat',
        icon: '🛡️',
        color: '#0f172a',
      },
    },
    recentQueue: [
      {
        id: '#APP-2026-8819',
        applicantName: 'Budi Santoso',
        nik: '3271048801920002',
        productName: 'Secure Life Plus',
        sumAssured: 'Rp 500.000.000',
        status: 'under_review',
        statusLabel: 'Under Review',
        slaMinutesLeft: 12,
        slaText: '12 min left',
      },
      {
        id: '#APP-2026-8820',
        applicantName: 'Siti Rahmawati',
        nik: '3174029104870001',
        productName: 'Health Guard Essential',
        sumAssured: 'Rp 250.000.000',
        status: 'submitted',
        statusLabel: 'Submitted',
        slaMinutesLeft: 26,
        slaText: '26 min left',
      },
      {
        id: '#APP-2026-8821',
        applicantName: 'Hendra Wijaya',
        nik: '3578017508840003',
        productName: 'Auto Shield Comprehensive',
        sumAssured: 'Rp 380.000.000',
        status: 'under_review',
        statusLabel: 'Under Review',
        slaMinutesLeft: 38,
        slaText: '38 min left',
      },
      {
        id: '#APP-2026-8822',
        applicantName: 'Maya Anggraini',
        nik: '3201099203950004',
        productName: 'Secure Life Plus',
        sumAssured: 'Rp 1.000.000.000',
        status: 'under_review',
        statusLabel: 'Under Review',
        slaMinutesLeft: 45,
        slaText: '45 min left',
      },
      {
        id: '#APP-2026-8823',
        applicantName: 'Dimas Prasetyo',
        nik: '5171038902910005',
        productName: 'Health Guard Essential',
        sumAssured: 'Rp 150.000.000',
        status: 'approved',
        statusLabel: 'Approved',
        slaMinutesLeft: 0,
        slaText: 'Selesai',
      },
    ],
    slaDistribution: {
      averageSlaMinutes: 18.4,
      averageSlaText: '18.4 Menit',
      targetMinutes: 60,
      complianceRateText: 'Target batas: < 60 Menit (98.4% Kepatuhan)',
      statuses: [
        {
          label: 'Disetujui (Approved)',
          countText: '1.142 (88.9%)',
          percentage: 88.9,
          color: '#10b981',
        },
        {
          label: 'Dalam Review (Under Review)',
          countText: '28 (2.2%)',
          percentage: 8.0, // Scaled for visual progress
          color: '#f59e0b',
        },
        {
          label: 'Pengajuan Baru (Submitted)',
          countText: '14 (1.1%)',
          percentage: 5.0,
          color: '#2563eb',
        },
        {
          label: 'Ditolak / Dokumen Kurang',
          countText: '100 (7.8%)',
          percentage: 7.8,
          color: '#ef4444',
        },
      ],
    },
    topProducts: [
      {
        rank: 1,
        rankBadge: '🏆 #1 Kontributor',
        rankBadgeBg: 'bg-amber-100 border border-amber-300',
        rankBadgeColor: 'text-amber-800',
        category: 'ASURANSI JIWA',
        categoryColor: 'text-purple-600',
        name: 'Secure Life Plus',
        volumeFormatted: 'Rp 4.25 Miliar',
        activePoliciesCount: 612,
        lossRatioText: '14.2% Klaim',
        lossRatioStatus: '(Sehat)',
        lossRatioColor: 'text-emerald-600',
        slug: 'secure-life-plus',
      },
      {
        rank: 2,
        rankBadge: '🥈 #2 Kontributor',
        rankBadgeBg: 'bg-slate-100 border border-slate-300',
        rankBadgeColor: 'text-slate-700',
        category: 'ASURANSI KESEHATAN',
        categoryColor: 'text-blue-600',
        name: 'Health Guard Essential',
        volumeFormatted: 'Rp 2.80 Miliar',
        activePoliciesCount: 384,
        lossRatioText: '18.6% Klaim',
        lossRatioStatus: '(Sehat)',
        lossRatioColor: 'text-emerald-600',
        slug: 'health-guard-essential',
      },
      {
        rank: 3,
        rankBadge: '🥉 #3 Kontributor',
        rankBadgeBg: 'bg-orange-100 border border-orange-300',
        rankBadgeColor: 'text-orange-800',
        category: 'ASURANSI KENDARAAN',
        categoryColor: 'text-emerald-600',
        name: 'Auto Shield Comprehensive',
        volumeFormatted: 'Rp 1.37 Miliar',
        activePoliciesCount: 146,
        lossRatioText: '24.1% Klaim',
        lossRatioStatus: '(Normal)',
        lossRatioColor: 'text-amber-600',
        slug: 'auto-shield-comprehensive',
      },
    ],
  };

  async getDashboardData(): Promise<DashboardData> {
    return Promise.resolve(structuredClone(this.data));
  }
}
